# Generated by Django 4.1.3 on 2022-12-06 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('Visa', 4), ('MasterCard', 5)], default='Visa', max_length=10)),
                ('card_number', models.CharField(max_length=16)),
                ('card_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_valid_date', models.IntegerField(choices=[(12, 'Card for 12'), (6, 'Card for 6'), (1, 'Card for 12')])),
                ('card_use_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_balance', models.IntegerField(default=0)),
                ('card_status', models.BooleanField(default=False)),
            ],
        ),
    ]
