# Generated by Django 4.1.7 on 2023-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_transaction_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="card",
            name="card_valid_date",
            field=models.IntegerField(
                choices=[(12, "Card for 12"), (6, "Card for 6"), (1, "Card for 1")]
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="series",
            field=models.CharField(default="Visa", max_length=10),
        ),
    ]
