# Generated by Django 4.1.7 on 2023-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cards", "0002_card_card_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_level_membership",
            field=models.IntegerField(
                choices=[(1, "bronze"), (2, "gold"), (3, "platinum")], default=1
            ),
        ),
    ]
